// GENERATED — do not edit by hand. The GWT-RPC field schema for the SISPAD peticiones
// object graph (ADR-020). Each key is a Java class name; each value encodes that class's
// deserialize field order, one char per field: o=readObject s=readString i=readInt
// (int/boolean/short) l=readLong (2 tokens) d=readDouble L=collection M=map. Object/primitive
// arrays are handled by the "[" sig prefix in the reader, not here.
//
// DERIVED first-hand from the compiled GWT permutation deserializers (no third-party GWT
// library — ADR-004): strong-name A4775626553B7F6CC42EAB2808331B0E, module sispadinternet
// (GWT 2.0.3). Keyed by CLASS NAME (the per-type CRC in the wire sig rotates on SII recompile;
// the field layout does not). Regenerate with docs/sii-contract/peticiones-schema-extract.py.

/** class name → per-field op string (see header). */
export const GWT_SCHEMA: Readonly<Record<string, string>> = {
  'cl.sii.sdi.core.web.aa.gwt.shared.SdiSerializableServiceException': 's',
  'cl.sii.sdi.did.siger2.to.BienioTo': 'sss',
  'cl.sii.sdi.did.siger2.to.CalidadJuridicaTo': 'sss',
  'cl.sii.sdi.did.siger2.to.CargoTo': 'ss',
  'cl.sii.sdi.did.siger2.to.ContractualTo': 'ssssss',
  'cl.sii.sdi.did.siger2.to.CredencialTo': 'ssssss',
  'cl.sii.sdi.did.siger2.to.DefinicionEstadosTo': 'iiiiiiii',
  'cl.sii.sdi.did.siger2.to.DepartamentoTo': 'sss',
  'cl.sii.sdi.did.siger2.to.DomicilioTo': 'sssssssss',
  'cl.sii.sdi.did.siger2.to.EscalafonTo': 'sssssss',
  'cl.sii.sdi.did.siger2.to.GradoTo': 's',
  'cl.sii.sdi.did.siger2.to.GrupoAtencionTo': 'sss',
  'cl.sii.sdi.did.siger2.to.GrupoTo': 'sss',
  'cl.sii.sdi.did.siger2.to.HorarioTo': 'ssssso',
  'cl.sii.sdi.did.siger2.to.InformacionlFuncionarioTo': 'sssssssss',
  'cl.sii.sdi.did.siger2.to.LicenciaTo': '',
  'cl.sii.sdi.did.siger2.to.LocalTo': 'ssssssssss',
  'cl.sii.sdi.did.siger2.to.MarcacionTo': '',
  'cl.sii.sdi.did.siger2.to.PermisoTo': 'ss',
  'cl.sii.sdi.did.siger2.to.RegionalTo': 'sss',
  'cl.sii.sdi.did.siger2.to.RelacionContractualTo': 'oooooooooooooo',
  'cl.sii.sdi.did.siger2.to.SubroganteTo': '',
  'cl.sii.sdi.did.siger2.to.TipoJefaturaTo': 'sssss',
  'cl.sii.sdi.did.siger2.to.UbicacionOrganigramaTo': 'soooso',
  'cl.sii.sdi.did.siger2.to.UnidadTo': 'sss',
  'cl.sii.sdi.did.siger2.to.funcion.FuncionInformalTo': 'sss',
  'cl.sii.sdi.did.siger2.to.funcionario.FuncionarioTo': 'ooooioooo',
  'cl.sii.sdi.difsj.sispad.to.ActaRenunciaDatosImpresionTo': 'ssssssssssssosssososossss',
  'cl.sii.sdi.difsj.sispad.to.AutorizacionModeloMaquinaRegistradoraTo':
    'ooossoososoosoooossoooosooos',
  'cl.sii.sdi.difsj.sispad.to.AutorizacionOtroSistemaTo': 'sooooosssssooooo',
  'cl.sii.sdi.difsj.sispad.to.AutorizacionSispadTo': 'sooosooo',
  'cl.sii.sdi.difsj.sispad.to.CamposEntradaTo': 'sooosoooo',
  'cl.sii.sdi.difsj.sispad.to.ContribuyentePeticionTo': 'oooooo',
  'cl.sii.sdi.difsj.sispad.to.DocumentoMateriaTo': 'osoooooo',
  'cl.sii.sdi.difsj.sispad.to.DocumentoPerdidoTo': 'soooosossosoo',
  'cl.sii.sdi.difsj.sispad.to.DocumentoPeticionTo': 'ssosssssoossossooosssoo',
  'cl.sii.sdi.difsj.sispad.to.DocumentoTo': 'ssoooo',
  'cl.sii.sdi.difsj.sispad.to.EstadoPeticionTo': 'oooooooosssooooooooo',
  'cl.sii.sdi.difsj.sispad.to.EstadoTo': 'soooo',
  'cl.sii.sdi.difsj.sispad.to.FormularioPeticionTo': 'ssoossososooo',
  'cl.sii.sdi.difsj.sispad.to.HojaTrabajoGeneralTo': 'ooosssosoossssssssosooooo',
  'cl.sii.sdi.difsj.sispad.to.InformeRespaldoTo': 'ssssssoosssssssssssos',
  'cl.sii.sdi.difsj.sispad.to.InformeTribunalesTo': 'ooossoosooooooossoooosooos',
  'cl.sii.sdi.difsj.sispad.to.LibroPerdidoTo': 'ooooososoooosoo',
  'cl.sii.sdi.difsj.sispad.to.MaquinaRegistradoraTo': 'osooossooo',
  'cl.sii.sdi.difsj.sispad.to.MateriaPerdidaDocumentosTo': 'oooosoooosooooossoooosooos',
  'cl.sii.sdi.difsj.sispad.to.MateriaTo': 'oooossoooosooos',
  'cl.sii.sdi.difsj.sispad.to.NotaResolutorTo': 'osooo',
  'cl.sii.sdi.difsj.sispad.to.NotificacionMotivoTo': 'oo',
  'cl.sii.sdi.difsj.sispad.to.NotificacionTo':
    'ooosssoossosssssososososssooossssssossooososooososo',
  'cl.sii.sdi.difsj.sispad.to.PeticionTo':
    'ssossoosooooosssssoooooosooolssssssoossoosssoooooooososssssoooosssssssoooooosoooloooosooooolllllooooo',
  'cl.sii.sdi.difsj.sispad.to.ReceptorTo': 'oooso',
  'cl.sii.sdi.difsj.sispad.to.ResolucionTo': 'oooooooosssossoooossooosoos',
  'cl.sii.sdi.difsj.sispad.to.RespuestaTo': 'ooososossosososo',
  'cl.sii.sdi.difsj.sispad.to.SistemaPeticionTo': 'ooososoo',
  'cl.sii.sdi.difsj.sispad.to.SistemaReferenciaTo': 'oooso',
  'cl.sii.sdi.difsj.sispad.to.TareaTo': 'soooso',
  'cl.sii.sdi.difsj.sispad.to.TipoFormularioTo': 'osooo',
  'cl.sii.sdi.difsj.sispad.to.TomaRazonOtroSistemaTo': 'oossoosssoooooosssoososo',
  'cl.sii.sdi.difsj.sispad.to.TomaRazonTo': 'sooosssooooosssoososo',
  'cl.sii.sdi.difsj.sispad.to.ValorCampoEntradaTo': 'ooooooos',
  'cl.sii.sdi.oicc.core.to.ComunaTo': 'oso',
  'cl.sii.sdi.oicc.core.to.ContribuyenteFullTo': 'ooossssosoossoossooossoooo',
  'cl.sii.sdi.oicc.core.to.ContribuyenteTo': 'ssoossooossoooo',
  'cl.sii.sdi.oicc.core.to.DireccionFullTo': 'osssoooososooossssosoosooos',
  'cl.sii.sdi.oicc.core.to.DireccionTo': 'oossssosoosooos',
  'cl.sii.sdi.oicc.core.to.NegocioTo': 'soosoooooossssssossssioo',
  'cl.sii.sdi.oicc.core.to.RegionTo': 'os',
  'cl.sii.sdi.oicc.core.to.RegionalTo': 'oss',
  'cl.sii.sdi.oicc.core.to.SubTipoContribuyenteTo': 'oso',
  'cl.sii.sdi.oicc.core.to.UnidadOperativaTo': 'ssosoooo',
  'com.google.gwt.http.client.RequestException': 's',
  'com.google.gwt.i18n.client.impl.DateRecord': 'iiiiiiiiiiii',
  'com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException': 's',
  'com.google.gwt.user.client.rpc.SerializableException': 's',
  'com.google.gwt.user.client.rpc.SerializationException': 's',
  'java.io.IOException': 's',
  'java.lang.ArithmeticException': 's',
  'java.lang.ArrayIndexOutOfBoundsException': 's',
  'java.lang.ArrayStoreException': 's',
  'java.lang.Boolean': 'i',
  'java.lang.ClassCastException': 's',
  'java.lang.Exception': 's',
  'java.lang.IllegalArgumentException': 's',
  'java.lang.IllegalStateException': 's',
  'java.lang.IndexOutOfBoundsException': 's',
  'java.lang.Integer': 'i',
  'java.lang.Long': 'l',
  'java.lang.NegativeArraySizeException': 's',
  'java.lang.NullPointerException': 's',
  'java.lang.NumberFormatException': 's',
  'java.lang.RuntimeException': 's',
  'java.lang.Short': 'i',
  'java.lang.String': 's',
  'java.lang.StringIndexOutOfBoundsException': 's',
  'java.lang.UnsupportedOperationException': 's',
  'java.lang.annotation.AnnotationTypeMismatchException': 's',
  'java.sql.Date': 'l',
  'java.sql.Time': 'l',
  'java.sql.Timestamp': 'li',
  'java.util.ArrayList': 'L',
  'java.util.ConcurrentModificationException': 's',
  'java.util.Date': 'l',
  'java.util.EmptyStackException': 's',
  'java.util.LinkedList': 'L',
  'java.util.NoSuchElementException': 's',
  'java.util.Stack': 'L',
  'java.util.TooManyListenersException': 's',
  'java.util.Vector': 'L',
};
